#: coalib/output/LogPrinter.py:33 coalib/tests/output/LogPrinterTest.py:49
#: coalib/tests/processes/communication/LogMessageTest.py:49
#: coalib/processes/communication/LogMessage.py:31
msgid "DEBUG"
msgstr ""

#: coalib/output/LogPrinter.py:34 coalib/tests/output/LogPrinterTest.py:51
#: coalib/tests/processes/communication/LogMessageTest.py:47
#: coalib/processes/communication/LogMessage.py:32
msgid "WARNING"
msgstr ""

#: coalib/output/LogPrinter.py:35 coalib/tests/output/LogPrinterTest.py:44
#: coalib/tests/output/LogPrinterTest.py:46
#: coalib/tests/output/LogPrinterTest.py:53
#: coalib/tests/output/LogPrinterTest.py:56
#: coalib/tests/processes/communication/LogMessageTest.py:45
#: coalib/tests/processes/communication/LogMessageTest.py:51
#: coalib/processes/communication/LogMessage.py:33
msgid "ERROR"
msgstr ""

#. pragma: no cover
#: coalib/output/EspeakPrinter.py:32
msgid ""
"Espeak doesn't seem to be installed. You cannot use the voice output feature "
"without espeak. It can be downloaded from http://espeak.sourceforge.net/ or "
"installed via your usual package repositories."
msgstr ""

#. pragma: no cover
#: coalib/output/EspeakPrinter.py:37
msgid "Failed to execute espeak. An unknown error occurred."
msgstr ""

#: coalib/analysers/Analyser.py:81 coalib/tests/analysers/AnalyserTest.py:74
#: coalib/tests/analysers/AnalyserTest.py:84
msgid "Setting up analyser..."
msgstr ""

#: coalib/analysers/Analyser.py:83 coalib/tests/analysers/AnalyserTest.py:76
#: coalib/tests/analysers/AnalyserTest.py:85
msgid "Running analyser..."
msgstr ""

#: coalib/analysers/Analyser.py:85 coalib/tests/analysers/AnalyserTest.py:78
#: coalib/tests/analysers/AnalyserTest.py:86
msgid "Tearing down analyser..."
msgstr ""

#: coalib/analysers/Analyser.py:91
msgid ""
"Unknown failure in worker process.\n"
"Exception: {}\n"
"Traceback:\n"
"{}"
msgstr ""

#. debug message contains custom content, dont test this here
#: coalib/analysers/Analyser.py:94 coalib/tests/analysers/AnalyserTest.py:88
msgid "An unknown failure occurred and an analyzer run is aborted."
msgstr ""

#: coalib/analysers/helpers/OldResult.py:68
msgid "Comparision of a Result with a non-Result is impossible."
msgstr ""

#: coalib/analysers/helpers/OldResult.py:71
msgid "Comparision of results affecting different files is impossible."
msgstr ""

#: coalib/misc/StringConstants.py:19
msgid ""
"This is a bug. We are sorry for the inconvenience. Please contact the "
"developers if this happens more than once."
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "on"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "y"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "yes"
msgstr ""

#: coalib/misc/StringConstants.py:28
#: coalib/tests/misc/StringConverterTest.py:63
msgid "yeah"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "sure"
msgstr ""

#: coalib/misc/StringConstants.py:28
msgid "true"
msgstr ""

#: coalib/misc/StringConstants.py:29
msgid "definitely"
msgstr ""

#: coalib/misc/StringConstants.py:29
msgid "yup"
msgstr ""

#: coalib/misc/StringConstants.py:29
msgid "right"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "off"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "n"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "no"
msgstr ""

#: coalib/misc/StringConstants.py:37
#: coalib/tests/misc/StringConverterTest.py:67
msgid "nope"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "nah"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "false"
msgstr ""

#: coalib/misc/StringConstants.py:37
msgid "wrong"
msgstr ""

#. Do not change this translation without changing it in the code also!
#: coalib/tests/analysers/AnalyserTest.py:40
#: coalib/tests/analysers/AnalyserTest.py:77 coalib/tests/misc/i18nTest.py:44
#: coalib/tests/misc/i18nTest.py:48 coala:24
msgid "A string to test translations."
msgstr ""

#. Something's gone wrong
#: coala:27
msgid "Program terminated by user."
msgstr ""
